In [1]:
%pylab
import pandas as pd
import torch

# Exploring Pytorch from http://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html



Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


In [2]:
x = torch.Tensor(5,3)

In [3]:
x


 0.0000e+00  8.5899e+09  0.0000e+00
 8.5899e+09  9.8091e-45  0.0000e+00
-6.0290e+07  4.5916e-41 -9.0338e-05
 4.5776e-41 -3.1921e-06  4.5776e-41
 0.0000e+00  8.5899e+09 -3.5002e-03
[torch.FloatTensor of size 5x3]

In [4]:
x = torch.rand(5,3)

In [5]:
x


 0.4164  0.9430  0.3157
 0.1858  0.6310  0.5543
 0.6195  0.3359  0.9431
 0.1693  0.2338  0.0641
 0.9217  0.1967  0.0596
[torch.FloatTensor of size 5x3]

In [6]:
y = torch.rand(5,3)

In [7]:
y


 0.4811  0.1390  0.2908
 0.2304  0.7038  0.4300
 0.5630  0.6987  0.9544
 0.5612  0.9455  0.2335
 0.3034  0.1703  0.2379
[torch.FloatTensor of size 5x3]

In [8]:
x+y


 0.8975  1.0820  0.6065
 0.4162  1.3348  0.9843
 1.1825  1.0346  1.8976
 0.7305  1.1793  0.2976
 1.2251  0.3670  0.2974
[torch.FloatTensor of size 5x3]

In [9]:
x*y


 0.2003  0.1311  0.0918
 0.0428  0.4441  0.2383
 0.3488  0.2347  0.9002
 0.0950  0.2211  0.0150
 0.2796  0.0335  0.0142
[torch.FloatTensor of size 5x3]

In [10]:
x/y


 0.8655  6.7841  1.0854
 0.8062  0.8965  1.2890
 1.1005  0.4807  0.9882
 0.3017  0.2473  0.2746
 3.0384  1.1552  0.2504
[torch.FloatTensor of size 5x3]

In [11]:
torch.add(x,y)-(x+y)


 0  0  0
 0  0  0
 0  0  0
 0  0  0
 0  0  0
[torch.FloatTensor of size 5x3]

In [12]:
result = torch.Tensor(5,3)

In [13]:
torch.add(x,y, out=result)
print(result)


 0.8975  1.0820  0.6065
 0.4162  1.3348  0.9843
 1.1825  1.0346  1.8976
 0.7305  1.1793  0.2976
 1.2251  0.3670  0.2974
[torch.FloatTensor of size 5x3]



In [14]:
y.add_(x)


 0.8975  1.0820  0.6065
 0.4162  1.3348  0.9843
 1.1825  1.0346  1.8976
 0.7305  1.1793  0.2976
 1.2251  0.3670  0.2974
[torch.FloatTensor of size 5x3]

In [15]:
a = torch.ones(5)

In [16]:
a


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

In [17]:
b = a.numpy()

In [18]:
b

array([ 1.,  1.,  1.,  1.,  1.], dtype=float32)

In [19]:
a.add_(1)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

In [20]:
b

array([ 2.,  2.,  2.,  2.,  2.], dtype=float32)

In [21]:
# Torch tensor and numpy tensor shares the same memory slot!


In [22]:
a = np.ones(5)

In [23]:
a

array([ 1.,  1.,  1.,  1.,  1.])

In [24]:
b = torch.from_numpy(a)

In [25]:
b


 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

In [26]:
a=a*2

In [27]:
b


 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

In [28]:
a

array([ 2.,  2.,  2.,  2.,  2.])

In [29]:
b


 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

In [30]:
b = b*2

In [31]:
b


 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]

In [32]:
a

array([ 2.,  2.,  2.,  2.,  2.])

In [33]:
np.add(a, 1, out=a)

array([ 3.,  3.,  3.,  3.,  3.])

In [34]:
## Start with next session.

from torch.autograd import Variable

In [35]:
x = Variable(torch.ones(2,2), requires_grad=True) # Why requires_grad ? Seems to work anyway.

In [36]:
x

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [37]:
y = x + 2

In [38]:
y

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]

In [39]:
x_2 = Variable(torch.ones(2,2))

In [40]:
x_2

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [41]:
x_2 ++ 2

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]

In [42]:
y

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]

In [43]:
print(y.grad_fn)

In [44]:
z = y * y * 3
out = z.mean()
print(z, out)

Variable containing:
 27  27
 27  27
[torch.FloatTensor of size 2x2]
 Variable containing:
 27
[torch.FloatTensor of size 1]



In [45]:
out.backward()

In [46]:
print(x.grad)

Variable containing:
 4.5000  4.5000
 4.5000  4.5000
[torch.FloatTensor of size 2x2]



In [47]:
x

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [48]:
# Ok. The backward function is backpropagation for the variable... Pretty cool, not sure just yet when to use it.
# the .grad function is the derivative for the backprop...

In [49]:
x = torch.randn(3)

In [50]:
x = Variable(torch.randn(3), requires_grad=True)

In [51]:
x

Variable containing:
-0.7827
-1.3807
 2.0649
[torch.FloatTensor of size 3]

In [52]:
y = x *2

In [53]:
y

Variable containing:
-1.5653
-2.7615
 4.1298
[torch.FloatTensor of size 3]

In [54]:
while y.data.norm() < 1000:
    y = y * 2

print(y)

Variable containing:
 -400.7260
 -706.9375
 1057.2218
[torch.FloatTensor of size 3]



In [55]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])

In [56]:
gradients


 1.0000e-01
 1.0000e+00
 1.0000e-04
[torch.FloatTensor of size 3]

In [57]:
y.backward(gradients)

In [58]:
print(x.grad)

Variable containing:
  51.2000
 512.0000
   0.0512
[torch.FloatTensor of size 3]



In [59]:
# This I do not understand... Need to check this again
# the autograd is for back propagation in the neural network.

In [60]:
# Next learning module, creating a neural net.

In [61]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [132]:

dtype = torch.FloatTensor

N, D_in, H, D_out = 64, 1000, 100, 10

x = Variable(torch.randn(N, D_in).type(dtype), requires_grad=False)
y = Variable(torch.randn(N, D_out).type(dtype), requires_grad=False)

In [148]:
w1 = Variable(torch.randn(D_in, H).type(dtype), requires_grad=True)
w2 = Variable(torch.randn(H, D_out).type(dtype), requires_grad=True)


Variable containing:
 6.8819e+00 -4.7579e+00 -1.2158e+00  ...   4.0879e+00 -2.2503e+00 -8.5142e-01
 3.9815e+00 -1.6308e+00 -2.1050e+00  ...  -5.0594e+00 -1.4911e+00  2.0968e+00
-2.1520e+00 -1.3344e+00 -4.8168e+00  ...   2.9763e+00  2.2032e-01  2.8189e+00
                ...                   ⋱                   ...                
 1.6242e+00  2.4084e+00 -7.3878e-01  ...   1.8846e+00  1.6455e-01  3.0424e+00
 2.4516e+00 -4.0589e+00 -2.6730e-01  ...   3.5395e+00 -3.2026e+00  4.0952e+00
-2.7240e+00 -1.7947e+00 -1.1664e+00  ...  -1.1634e+00 -2.2169e+00  8.5387e+00
[torch.FloatTensor of size 1000x100]

In [141]:
learning_rate = 1e-6

In [156]:
y_pred = x.mm(w1).clamp(min=0).mm(w2)

w1.grad.data.zero_()
w2.grad.data.zero_()



    0     0     0  ...      0     0     0
    0     0     0  ...      0     0     0
    0     0     0  ...      0     0     0
       ...          ⋱          ...       
    0     0     0  ...      0     0     0
    0     0     0  ...      0     0     0
    0     0     0  ...      0     0     0
[torch.FloatTensor of size 100x10]

In [158]:
y_pred = x.mm(w1).clamp(min=0).mm(w2)
loss = (y_pred - y).pow(2).sum()

loss.backward()

for t in range(500):
    
    y_pred = x.mm(w1).clamp(min=0).mm(w2)
    
    loss = (y_pred - y).pow(2).sum()
    
    print(t, loss.data[0])
    
    w1.grad.data.zero_()
    w2.grad.data.zero_()
    
    loss.backward()
    
    w1.data -= learning_rate * w1.grad.data
    w2.data -= learning_rate * w2.grad.data
    

0 29134716.0
1 24819738.0
2 25413290.0
3 26990056.0
4 26491644.0
5 22343314.0
6 15840646.0
7 9660226.0
8 5444684.0
9 3075257.25
10 1858320.0
11 1237979.375
12 905452.4375
13 710583.875
14 583744.3125
15 493153.46875
16 423731.3125
17 367969.15625
18 321832.75
19 282979.90625
20 249900.953125
21 221451.796875
22 196858.4375
23 175489.03125
24 156866.453125
25 140542.0625
26 126166.9765625
27 113509.421875
28 102317.65625
29 92385.6953125
30 83543.796875
31 75659.421875
32 68617.4609375
33 62316.40234375
34 56661.34375
35 51578.96875
36 47007.98046875
37 42882.48828125
38 39145.9375
39 35768.0625
40 32710.734375
41 29940.43359375
42 27427.0546875
43 25143.28125
44 23065.9296875
45 21176.001953125
46 19453.060546875
47 17881.60546875
48 16446.40625
49 15134.8359375
50 13935.2021484375
51 12838.4736328125
52 11834.00390625
53 10913.099609375
54 10068.72265625
55 9293.5224609375
56 8581.6796875
57 7927.4775390625
58 7326.24755859375
59 6773.0146484375
60 6263.84521484375
61 5795.52734375
62

479 2.3784799850545824e-05
480 2.3552682250738144e-05
481 2.3207172489492223e-05
482 2.3125152438296936e-05
483 2.2881149561726488e-05
484 2.2613787223235704e-05
485 2.2384292606147937e-05
486 2.218334520875942e-05
487 2.1993526388541795e-05
488 2.1896899852436036e-05
489 2.1632309653796256e-05
490 2.1463965822476894e-05
491 2.1285821276251227e-05
492 2.1210302293184213e-05
493 2.099159246427007e-05
494 2.0802737708436325e-05
495 2.062277235381771e-05
496 2.0285940991016105e-05
497 2.0157725884928368e-05
498 2.0065017451997846e-05
499 1.995091406570282e-05


In [ ]:
y_pred = x.mm

In [116]:
a = Variable(torch.ones(3,3)*2)
b = Variable(torch.from_numpy(np.array([(1,2,3),(4,5,6),(7,8,9)])).type(torch.FloatTensor))

In [130]:
a.mm(b).mm(w1)

RuntimeError: size mismatch, m1: [3 x 3], m2: [1000 x 100] at /Users/soumith/miniconda2/conda-bld/pytorch_1502000975045/work/torch/lib/TH/generic/THTensorMath.c:1293

In [126]:
a

Variable containing:
 2  2  2
 2  2  2
 2  2  2
[torch.FloatTensor of size 3x3]

In [123]:
b

Variable containing:
 1  2  3
 4  5  6
 7  8  9
[torch.FloatTensor of size 3x3]

In [119]:
a*b

Variable containing:
  2   4   6
  8  10  12
 14  16  18
[torch.FloatTensor of size 3x3]